const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const manifest=()=>JSON.parse(fs.readFileSync(__dirname+'/../../src/n8n/en-writing.nodes.json','utf8'));
function code(name,input,context){const n=manifest().nodes.find(n=>n.name===name);assert.ok(n,'missing '+name);return new Function('$input','$',n.parameters.jsCode)({all:()=>input.map(json=>({json})),first:()=>({json:input[0]})},key=>{assert.ok(key in context,'unexpected dependency '+key);return {first:()=>({json:context[key]})};})[0].json;}
const clone=x=>JSON.parse(JSON.stringify(x));
function context(){return {content_id:'fixture',story_id:'story_1',story_mode:'news',writer_context:{config:{language:'en-US',content_type:'linkedin_longform'}},writer_brief:{schema:'writer_brief.v3',language:'en-US',story_mode:'news',article_intent:{reader_change:'Understand the change.',thesis:null},editorial_instructions:{human_instructions:'Preserve the announced status.',editor_note:''},movements:[],quotations:[]},writer_invocation_receipt:{authorization_kind:'controlled_test',target_language:'en-US'}};}
const draft='# Original\n\nA sourced draft with [evidence](https://example.invalid/a).';
function editInput(ctx=context()){return code('V2 EN Edit Input',[{output:draft}],{'Writer Invocation Gate':ctx});}
function preview(result,input=editInput()){return code('V2 EN Preview',[result],{'V2 EN Edit Input':input});}
test('draft binds English context and preserves brief without inventing a thesis',()=>{const c=context(),before=clone(c),p=editInput(c);assert.equal(p.article_to_polish,draft);assert.deepEqual(p.writer_brief,c.writer_brief);assert.equal(p.writer_brief.article_intent.thesis,null);assert.deepEqual(c,before);});
test('Chinese context rejected before editing',()=>{const c=context();c.writer_context.config.language='zh-CN';assert.throws(()=>editInput(c),/English/);});
test('brief-language mismatch rejected',()=>{const c=context();c.writer_brief.language='zh-CN';assert.throws(()=>editInput(c),/English/);});
test('empty draft rejected',()=>assert.throws(()=>code('V2 EN Edit Input',[{output:''}],{'Writer Invocation Gate':context()}),/empty/));
test('multiple drafts rejected',()=>assert.throws(()=>code('V2 EN Edit Input',[{output:draft},{output:draft}],{'Writer Invocation Gate':context()}),/one draft/));
test('completed preview preserves exact edited text, draft, identity and authorization',()=>{const text='# Edited\n\nNew rhythm.\n\n## Detail\n\nThe same [evidence](https://example.invalid/a).\n';const p=preview({output:text});assert.equal(p.schema,'writing_preview.v1');assert.equal(p.article_markdown,text);assert.equal(p.draft_markdown,draft);assert.equal(p.content_id,'fixture');assert.equal(p.language,'en-US');assert.equal(p.editing_status,'completed');assert.equal(p.writer_invocation_receipt.authorization_kind,'controlled_test');assert.deepEqual(p.publication,{state:'NOT_PUBLISHED',url:null});});
for(const [name,result] of [['error',{error:{message:'simulated'},output:'# Plausible\n\nIgnore me.'}],['empty',{output:''}],['object',{output:{status:'PASS'}}],['no title',{output:'Plain text.'}],['two titles',{output:'# One\n\nText.\n\n# Two\n\nText.'}],['title only',{output:'# Only title'}]])test(name+' returns untouched original for review',()=>{const p=preview(result);assert.equal(p.status,'review_required');assert.equal(p.editing_status,'failed');assert.equal(p.article_markdown,draft);assert.equal(p.draft_markdown,draft);assert.equal(code('V2 EN Review Required',[p],{}),p);});
test('hold terminal refuses a completed preview',()=>assert.throws(()=>code('V2 EN Review Required',[preview({output:'# Edited\n\nBody.'})],{}),/review-required/));
test('preview refuses multiple editor results rather than choosing one',()=>assert.throws(()=>code('V2 EN Preview',[{output:'# One\n\nA.'},{output:'# Two\n\nB.'}],{'V2 EN Edit Input':editInput()}),/one edit/));
test('only completed previews route to visuals and unmatched states go to hold validation',()=>{const n=manifest().nodes.find(n=>n.name==='V2 EN Preview Route');assert.equal(n.parameters.rules.values.length,1);const expression=n.parameters.rules.values[0].conditions.conditions[0].leftValue;const fn=new Function('$json','return '+expression.slice(3,-2).trim());assert.equal(fn(preview({output:'# Good\n\nText.'})),true);assert.equal(fn(preview({error:'failure'})),false);assert.equal(n.parameters.options.fallbackOutput,'extra');});
test('English model prompts consume current brief and distinguish News from analysis',()=>{const ns=manifest().nodes;const w=ns.find(x=>x.name==='V2 EN Lead Writer').parameters,e=ns.find(x=>x.name==='V2 EN Line & Rhythm Editor').parameters;assert.match(w.text,/writer_brief/);assert.match(w.options.systemMessage,/News/);assert.match(w.options.systemMessage,/thesis/);assert.match(e.text,/writer_brief/);assert.doesNotMatch(e.text,/review_issues|review_status|source_branch/);});
