// Temporary native n8n probe. Reduced public-material fixture, not formal approval.
const which = $input.first().json.body?.test_case || 'reassessed';
const copy = x => JSON.parse(JSON.stringify(x));
const id = 'test:handoff-native-20261003';
const title = 'Stripe 拟收购 OpenRouter：模型路由为何进入支付公司的版图，现有用户会怎样？';
const promise = '读者能弄清这笔交易到了哪一步、OpenRouter 的模型路由具体有什么用、双方各自如何解释结合，以及现有用户的使用方式与公司承诺之间有哪些直接联系。';
const human = '按公告当日材料研究，保留各方原话与归属；不要把签约写成交割完成。';
const source = (ref,url) => ({ref,url,title:ref,claim_eligible:true,retrieval_status:'body_fetched'});
const s1 = source('initial:S01','https://stripe.com/newsroom/news/stripe-agrees-to-acquire-openrouter');
const s2 = source('supplementary:S01','https://cline.bot/blog/cline-3-8-0-workflow-integration-account-management-and-provider-optimization');
const c1 = {ref:'initial:C01',statement:'Stripe 在 2026 年 8 月 19 日公告中宣布已同意收购 OpenRouter；应写为达成收购协议，而不是交割完成。',source_refs:[s1.ref],status:'confirmed'};
const c2 = {ref:'supplementary:C01',statement:'Cline 发布记录说明可按吞吐量、价格或延迟选择底层提供商路由优先级。',source_refs:[s2.ref],status:'attributed'};
const q1 = {ref:'initial:QT01',text_original:'Stripe is building the economic infrastructure for AI, and together with OpenRouter we’ll help businesses maximize profitability by routing their requests intelligently and spending their tokens efficiently.',speaker:'Patrick Collison',attribution:'Stripe 官方公告引语，并非本研究采访。',source_ref:s1.ref};
const q2 = {ref:'supplementary:QT01',text_original:"One of the most powerful additions in 3.8.0 is the new 'Sort underlying provider routing' setting. This feature gives you more control over how Cline and OpenRouter route your requests across different AI providers.",speaker:'Nick Baumann',attribution:'Cline 官方书面发布记录，并非本研究采访。',source_ref:s2.ref};
const old = {sources:[s1],claims:[c1],quotations:[q1]};
const added = {sources:[s2],claims:[c2],quotations:[q2]};
const p = {working_title:title,reader_promise:promise,opening:{material_refs:[c1.ref]},story_path:[{job:'公告与使用记录。',material_refs:[c1.ref,q1.ref]}],quotation_refs:[q1.ref]};
const current = {...copy(p),story_path:[{job:'公告与使用记录。',material_refs:[c1.ref,c2.ref,q1.ref,q2.ref]}],quotation_refs:[q1.ref,q2.ref]};
const ctx = {content_id:id,topic_brief:'执行 557 的裁剪衍生测试，不重新核实新闻，不作正式审批。',human_instructions:human,materials:old};
const a = {story_id:'story_1',story_mode:'news',title,proposal:p,editor_note:'',additional_research_instructions:'',research_requests:[{question:'寻找公开使用记录。',required_for_story:true}]};
const validation = {valid:true,errors:[],checked_count:1,quotation_count:1};
const parent = {content_id:id,brief_content:'',editor_input:copy(ctx),quotation_validation:copy(validation)};
const work = {schema:'research_work_order.v1',content_id:id,story_id:'story_1',story_mode:'news',service_invoked:false,editor_input:copy(ctx),parent_context:parent,research_input:{content_id:id,human_instructions:'',final_narrative:{...copy(a),initial_human_instructions:human}}};
const candidate = {schema:'story_candidate.v1',content_id:id,story_id:'story_1',story_mode:'news',status:'ready',proposal:current,research_requests:[]};
let x = {schema:'selected_story_reassessment_result.v1',content_id:id,story_id:'story_1',story_mode:'news',status:'ready_for_writer_handoff',next_action:'prepare_writing_handoff',writing_authorized:false,research_loop_authorized:false,approved_story:copy(a),editor_input:{...copy(ctx),approved_story:copy(a),materials:{sources:[s1,s2],claims:[c1,c2],quotations:[q1,q2]}},candidate,selected_quotations:[{...q1,source_url:s1.url},{...q2,source_url:s2.url}],research_increment_receipt:{schema:'research_increment_receipt.v1',content_id:id,story_id:'story_1',story_mode:'news',status:'usable_materials',worker_research_status:'research_ready',service_invoked:true,requires_reassessment:true,accepted_materials:added,quotation_validation:copy(validation),research_work_order:work},test_context:{kind:'reduced_historical_fixture',source_execution:'557',formal_hitl:false,test_case:which}};
if (which === 'direct') x = {schema:'story_dispatch.v1',content_id:id,story_id:'story_1',story_mode:'news',next_action:'prepare_writing',selection_status:'selected',title,title_override:'',editor_note:'',additional_research_instructions:'',research_requests:[],approved_candidate:{...candidate,proposal:copy(p)},editor_input:copy(ctx),parent_context:parent,test_context:{kind:'synthetic_direct_ready',formal_hitl:false,test_case:which}};
else if (which === 'missing_source') x.editor_input.materials.sources.pop();
else if (which === 'quote_drift') x.selected_quotations[1].text_original = 'Invented quotation';
else if (which === 'unfinished') x.candidate.research_requests = [{required_for_story:true}];
else if (which === 'authorization') x.writing_authorized = true;
else if (which === 'identity') x.candidate.content_id = 'another-story';
else if (which !== 'reassessed') throw new Error('Unknown probe case');
return [{json:copy(x)}];
