const test=require('node:test'); const assert=require('node:assert/strict'); const fs=require('node:fs');
const src=fs.readFileSync(__dirname+'/../../src/n8n/main-validate-story-mode.js','utf8');
function ctx(){return {stage:'initial_research_ready',content_id:'c1',title:'Topic',human_instructions:'more use cases',materials:[{retrieval:{raw_content:'body'}}],selected_topic:{title:'Topic'},initial_research:{body_count:2},publication:{state:'NOT_PUBLISHED',url:null}};}
function run(output,c=ctx()){return new Function('$input','$',src)({first:()=>({json:output})},name=>{assert.equal(name,'Attach Initial Browser Sources');return {first:()=>({json:c})};})[0].json;}
test('news direction has no thesis and proceeds without narrative approval',()=>{const o=run({text:JSON.stringify({mode:'news',why_this_mode:'Event reporting is stronger than a separate thesis.',working_title:'A news title',reader_promise:'Understand the event and its actual use.',core_judgment:null,story_path:['What changed','How it is used','Different views']})});assert.equal(o.story_mode,'news');assert.equal(o.stage,'story_direction_ready');assert.equal(o.story_direction.core_judgment,null);assert.equal(o.human_instructions,'more use cases');});
test('deep direction requires one judgment and awaits one narrative approval',()=>{const o=run({output:{mode:'deep_analysis',why_this_mode:'Materials support a distinct judgment.',working_title:'A deep title',reader_promise:'Understand the mechanism and consequence.',core_judgment:'The product change moves the cost boundary.',story_path:['Concrete change','Mechanism','Counterweight','Consequence']}});assert.equal(o.story_mode,'deep_analysis');assert.equal(o.stage,'awaiting_narrative_approval');assert.equal(o.story_direction.core_judgment,'The product change moves the cost boundary.');});
test('news thesis is rejected without losing research context',()=>{const o=run({text:JSON.stringify({mode:'news',why_this_mode:'x',working_title:'T',reader_promise:'P',core_judgment:'forced thesis',story_path:['a','b']})});assert.equal(o.stage,'story_mode_review_required');assert.equal(o.materials.length,1);assert.match(o.story_mode_error.detail,/News/);});
test('model error preserves initial research',()=>{const o=run({error:'controlled model failure'});assert.equal(o.stage,'story_mode_review_required');assert.equal(o.initial_research.body_count,2);assert.equal(o.publication.state,'NOT_PUBLISHED');});
test('invalid json preserves context',()=>{const o=run({text:'not-json'});assert.equal(o.stage,'story_mode_review_required');assert.equal(o.story_mode_error.kind,'invalid_json');});
test('invalid input research context is rejected',()=>{const c=ctx();c.initial_research.body_count=0;assert.throws(()=>run({text:'{}'},c),/initial research context invalid/);});
