// No network/models: the counts below are test cases, not editorial quotas.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const file=path.join(__dirname,'../../src/n8n/visual-planning.nodes.json');
const paragraphs=['**速度还是价格？** 这个选择会改变请求的去向。','第二段说明费用如何显示。','第三段讨论平台与使用者的关系。'];
function preview(){return {schema:'writing_preview.v1',status:'draft',editing_status:'completed',content_id:'test:visual-planning',story_id:'story_1',story_mode:'news',language:'zh-CN',article_title:'阅读测试',article_markdown:'# 阅读测试\n\n'+paragraphs.join('\n\n'),draft_markdown:'# 原稿\n\n原稿必须保留。',warnings:[],publication:{state:'NOT_PUBLISHED',url:null}};}
function plan(n){return {schema:'visual_plan.v2',images_to_generate:Array.from({length:n+1},(_,i)=>({id:i?'IMG_'+i:'COVER_IMG',role:i?'body_illustration':'article_cover',visual_mode:'editorial_image',archetype_id:'SATIRIST_PEN_INK',format_preset:i?'inline_square':'linkedin_article_cover',placement:{mode:i?'after_paragraph':'cover_field',anchor:i?paragraphs[i-1]:''},purpose:'Show a distinct relationship.',scene:'Two plain objects at a fork.',alt_text:'岔路旁的两个物体',caption:i?'选择的方向':''}))};}
function nodes(){assert.ok(fs.existsSync(file),'visual seam configuration missing');return JSON.parse(fs.readFileSync(file,'utf8'));}
function run(name,json,source){const code=nodes().find(n=>n.name===name).parameters.jsCode;return vm.runInNewContext(`(function(){${code}\n})()`,{$input:{all:()=>[{json}],first:()=>({json})},$:n=>({first:()=>({json:source})})},{timeout:1000})[0].json;}
function check(p,source=preview()){return run('V2 Visual Plan Validator',{output:p},source);}
for(const n of [0,1,3]) test(`accepts cover plus ${n} body images without changing text`,()=>{const s=preview(),before=JSON.stringify(s),p=plan(n),out=check(p,s);assert.equal(out.visual_planning_status,'completed');assert.equal(out.visual_plan.counts.body,n);assert.equal(out.visual_plan.schema,'visual_plan_validated.v1');assert.equal(out.article_markdown,s.article_markdown);assert.equal(out.draft_markdown,s.draft_markdown);assert.equal(JSON.stringify(s),before);assert.equal(out.publication.state,'NOT_PUBLISHED');});
test('input keeps the supplied edition, not an English default, and rejects unfinished/empty inputs',()=>{const p=preview();assert.equal(run('V2 Visual Input',p).language,'zh-CN');for(const change of [{article_markdown:''},{status:'review_required'},{editing_status:'failed'}])assert.throws(()=>run('V2 Visual Input',{...p,...change}),/Visual input:/);});
test('schema removes body-image quota and accepts dynamic IDs',()=>{const s=JSON.parse(nodes().find(n=>n.name==='Structured Output Parser3').parameters.inputSchema);const a=s.properties.images_to_generate;assert.equal(a.minItems,1);assert.equal(a.maxItems,undefined);assert.equal(a.items.properties.id.enum,undefined);assert.ok(new RegExp(a.items.properties.id.pattern).test('IMG_12'));assert.ok(!new RegExp(a.items.properties.id.pattern).test('IMG_0'));});
test('duplicates, unknown IDs, nonexact/nonprose anchors and unsupported modes preserve draft as planning failure',()=>{for(const mutate of [p=>p.images_to_generate.push({...p.images_to_generate[1]}),p=>p.images_to_generate[1].id='IMG_9',p=>p.images_to_generate[1].placement.anchor='这个选择',p=>p.images_to_generate[1].placement.anchor='# 阅读测试',p=>p.images_to_generate[1].visual_mode='chart',p=>p.images_to_generate[1].prompt='not a planner field']){const p=plan(1);mutate(p);const out=check(p);assert.equal(out.visual_planning_status,'failed');assert.equal(out.visual_plan,null);assert.equal(out.article_markdown,preview().article_markdown);}});
test('failure/empty model response keeps both articles and does not expose raw errors',()=>{for(const result of [{error:{message:'private-key-value'}},{output:null},{output:{schema:'visual_plan.v2',images_to_generate:[]}}]){const out=run('V2 Visual Plan Validator',result,preview());assert.equal(out.visual_planning_status,'failed');assert.equal(out.draft_markdown,preview().draft_markdown);assert.ok(!JSON.stringify(out).includes('private-key-value'));}});
test('paragraph check respects fenced code and duplicate source text',()=>{const s=preview();s.article_markdown+='\n\n```txt\n\nnot a prose paragraph\n\n```';let p=plan(1);p.images_to_generate[1].placement.anchor='not a prose paragraph';assert.equal(check(p,s).visual_planning_status,'failed');s.article_markdown+='\n\n'+paragraphs[0];assert.equal(check(plan(1),s).visual_planning_status,'failed');});
module.exports={preview,plan,paragraphs};
